### PR TITLE
decorate login and signup also fix position botton in nav bar

### PR DESCRIPTION
**Pull request by zevenfox**
เ ท่ ม า ก | S o c o o l la

### CODE REVIEW

**Comment by jaybjackie** [comment]
Did you get this result?
image

I don't know way. But when I comment the lines about fetching api, It works fine

**Comment by jaybjackie** [comment]
And API Quota is used just about 60 %

**Comment by jaybjackie** [comment]
I found that in login page on user field. When I enter username I said I should input email. It might have to be email.
image

**Comment by zevenfox** [comment]
Me too but I think it's not from lines about fetching api cause I just reloaded the page about 5 time and then it work again
and I am not doing anything about  fetching api

**Comment by jaybjackie** [comment]
> Me too but I think it's not from lines about fetching api cause I just reloaded the page about 5 time and then it work again
> and I am not doing anything about fetching api

Yeah I got the same scenario. What the duck.

**Comment by zevenfox** [comment]
> > Me too but I think it's not from lines about fetching api cause I just reloaded the page about 5 time and then it work again
> > and I am not doing anything about fetching api
> 
> Yeah I got the same scenario. What the duck.



> I found that in login page on user field. When I enter username I said I should input email. It might have to be email.
> image

It is because I write the code input type="email"
but if you don't want it I can fix it.

**Comment by zevenfox** [comment]
> > > Me too but I think it's not from lines about fetching api cause I just reloaded the page about 5 time and then it work again
> > > and I am not doing anything about fetching api
> > 
> > 
> > Yeah I got the same scenario. What the duck.
> 
> > I found that in login page on user field. When I enter username I said I should input email. It might have to be email.
> > image
> 
> It is because I write the code input type="email" but if you don't want it I can fix it.

You can see it here [https://www.w3schools.com/tags/att_input_type.asp](url)

**Comment by jaybjackie** [comment]
Then I think  change the `username` to `email` instead, is good enough.
image

**Comment by zevenfox** [comment]
I concern that if user login with google Botton (same email as email in username) and he can not login with  username Botton . What do you think about this?

**Comment by jaybjackie** [comment]
Is there a possible way to handle same email on manual registration and email using Google Auth ?
I think it have a way but might take some time. No worry I'll help you find it.

But at first I concern about wrong name and its functionality(named username but needs email).

**Comment by zevenfox** [comment]
> Is there a possible way to handle same email on manual registration and email using Google Auth ? I think it have a way but might take some time. No worry I'll help you find it.
> 
> But at first I concern about wrong name and its functionality(named username but needs email).

As I saw the website such as Grammarly. It can use the same email from email Botton and google Botton  but password is not the same.But I think if we can handle same email and same password It may be hard but also It might be a way. Thanks a lot! now I'll do some Oauth , not Sure I can finish it today.
Screen Shot 2565-10-31 at 01 00 48

**Comment by jaybjackie** [comment]
> Did you get this result? image
> 
> I don't know why. But when I comment the lines about fetching api, It works fine

For this problem, I think it cause by API Provider last night.
I tried to do the same as last night to make sure it still error. But now it's work fine.
So, I think we can move on to do others task.
But if you have found the same problem again. We will need to do something about this.

**Pull request merged**
