### PR TITLE
add function in createmenu

### PR DESCRIPTION
**Pull request by JaofourthsOhappy**
Add ingredients can now add or delete multiple ingredients.
This contains almost exceptions, such as when users add the same ingredients, etc.

### CODE REVIEW

**Comment by jaybjackie** [comment]
I am reviewing now. Just a few minute please.

**Comment by jaybjackie** [comment]
The word `Create Your Menu` exceeded the underlying rectangle.
also can you change it to `Create Your Food`
And `Add my menu` in navigation bar to `Add my food`
Screenshot 2565-11-22 at 7 29 50 PM

**Comment by jaybjackie** [comment]
I was add ingredients name and quantity but without quantity unit.
The first two was add but unit display as `disable` and can be typing but cannot save new quantity unit.

image

**Comment by jaybjackie** [comment]
I was Create the food but when I clicked on the created food. This error was shown

Screenshot 2565-11-22 at 7 31 56 PM

**Review by jaybjackie — COMMENTED** [review]
Reviewed!

**Review by zevenfox — APPROVED** [review]
JS include some exception. That nice and this work to me.

**Pull request merged**
