### PR TITLE
fix create menu detail

### PR DESCRIPTION
**Pull request by JaofourthsOhappy**
-  Change User upload url image
-  Create page User create menu detail

### CODE REVIEW

**Review by Unikorn996 — APPROVED** [review]
It works.

**Comment by jaybjackie** [comment]
Please don't merge yet I will confirm again.

**Comment by jaybjackie** [comment]
image
It can create food. Good!

But one thing I notice here that ingredients didn't shown here even I clicked 'Add ingredient'
Screenshot 2565-11-29 at 9 31 37 PM

**Comment by Unikorn996** [comment]
> It can create food. Good!
> 
> But one thing I notice here that ingredients didn't shown here even I clicked 'Add ingredient' Screenshot 2565-11-29 at 9 31 37 PM

That's exactly the problem which I and another assignee are gonna fix it after this merge.

**Comment by jaybjackie** [comment]
I encounter this error when `loaddata` 
Screenshot 2565-11-30 at 8 54 41 PM

**Comment by zevenfox** [comment]
> I encounter this error when `loaddata`
> Screenshot 2565-11-30 at 8 54 41 PM
I already take a look at this and discuss this with forth. In my opinion I think that it is conflict with new data base that I just create or the data base that save food for user is the same with official and may be causing by data.json and delete migration that miss click? I will help debug this tmr

**Comment by jaybjackie** [comment]
> > I encounter this error when `loaddata`
> 
> > Screenshot 2565-11-30 at 8 54 41 PM
> 
> I already take a look at this and discuss this with forth. In my opinion I think that it is conflict with new data base that I just create or the data base that save food for user is the same with official and may be causing by data.json and delete migration that miss click? I will help debug this tmr
> 
> 

Roger that krub 🫡

**Review by jaybjackie — COMMENTED** [review]
Good

**Pull request merged**
