### PR TITLE
Improve CreateMenu page

### PR DESCRIPTION
**Pull request by Unikorn996**
Change input of description to textarea on CreateMenu page for a better look :)

### CODE REVIEW

**Review by jaybjackie — CHANGES_REQUESTED** [review]
It's very good that you put the condition to avoid blank input. Can you also modify in the ingredients too, It's must be great.

**Comment by Unikorn996** [comment]
> It's very good that you put the condition to avoid blank input. Can you also modify in the ingredients too, It's must be great.

Sure, I'm on it.

**Review by jaybjackie — COMMENTED** [review]
Is it possible to leave the ingredients blank when there is a ingredient added into the food?
image

**Comment by zevenfox** [comment]
> Is it possible to leave the ingredients blank when there is a ingredient added into the food?
> image

actually when it already have ingredient >=1 and all of Important box is Filled up. The function must allow user to create food no matter what.

**Review by jaybjackie — COMMENTED** [review]
Good to handle number condition.

**Comment by jaybjackie** [comment]
> > Is it possible to leave the ingredients blank when there is a ingredient added into the food?
> > image
> 
> actually when it already have ingredient >=1 and all of Important box is Filled up. The function must allow user to create food no matter what.

Still, Mickey explained very clear. I hope you can figure it out. 
If there is any problem, inform us.

**Comment by Unikorn996** [comment]
> > > Is it possible to leave the ingredients blank when there is a ingredient added into the food?
> > > image
> > 
> > 
> > actually when it already have ingredient >=1 and all of Important box is Filled up. The function must allow user to create food no matter what.
> 
> Still, Mickey explained very clear. I hope you can figure it out. @Unikorn996 If there is any problem, inform us.

The problem here is when you want to add the ingredient(s), you have to add one more blank ingredient field before you click create button. And if you don't, the amount of ingredients will be one less. And that one lost ingredient is the last ingredient you fill without adding another blank field.

**Comment by jaybjackie** [comment]
> > > > Is it possible to leave the ingredients blank when there is a ingredient added into the food?
> > > > image
> > > 
> > > 
> > > actually when it already have ingredient >=1 and all of Important box is Filled up. The function must allow user to create food no matter what.
> > 
> > 
> > Still, Mickey explained very clear. I hope you can figure it out. @Unikorn996 If there is any problem, inform us.
> 
> The problem here is when you want to add the ingredient(s), you have to add one more blank ingredient field before you click create button. And if you don't, the amount of ingredients will be one less. And that one lost ingredient is the last ingredient you fill without adding another blank field.

I tried leaving a blank line of ingredients but it's telling me to fill the blank any way.

As Mickey suggest above, to check when ingredient is > 0. So, we can leave it blank. Can you try with this logic? I think it makes sense and should works.

image

**Comment by Unikorn996** [comment]
> > > > > Is it possible to leave the ingredients blank when there is a ingredient added into the food?
> > > > > image
> > > > 
> > > > 
> > > > actually when it already have ingredient >=1 and all of Important box is Filled up. The function must allow user to create food no matter what.
> > > 
> > > 
> > > Still, Mickey explained very clear. I hope you can figure it out. @Unikorn996 If there is any problem, inform us.
> > 
> > 
> > The problem here is when you want to add the ingredient(s), you have to add one more blank ingredient field before you click create button. And if you don't, the amount of ingredients will be one less. And that one lost ingredient is the last ingredient you fill without adding another blank field.
> 
> I tried leaving a blank line of ingredients but it's telling me to fill the blank any way.
> 
> As Mickey suggest above, to check when ingredient is > 0. So, we can leave it blank. Can you try with this logic? I think it makes sense and should works.
> 
> image

I'm trying to find where could be the cause. Thanks.

**Comment by jaybjackie** [comment]
@Unikorn996
Now we can leave the ingredient blank. Then, the remaining problem is when `create food` without ingredients are added. It will raise an error. So, I suggest the way to handle this error.

Aim at ingredients length. User may add the ingredients, it's user's choice. What we can do is handle Error when create food

image

PS. feel free to suggest the other ways.

**Review by jaybjackie — APPROVED** [review]

**Pull request merged**
